### ISSUE TITLE
"token-account-history" error for the faucet

### ISSUE THREAD

**Issue by ilzheev** [AccumulateNetwork/accumulate#202]
Running latest develop (commit ca5973299bbffc88f7531848811c26912a837f14)

Init network:
```
go run ./cmd/accumulated init -n "Badlands" --relay-to "Badlands"
```

Run node:
```
go run ./cmd/accumulated run -n 0 
```

API request:
```json
{
"jsonrpc": "2.0",
"id": 4,
"method": "token-account-history",
"params": {
"url": "acc://7117c50f04f1254d56b704dc05298912deeb25dbc1d26ef6/ACME",
"start": 0,
"limit": 10
}
}
```

API response:
```json
{
"jsonrpc": "2.0",
"error": {
"code": -32802,
"message": "Validation Error",
"data": "jsonrpc2.Error{Code:ErrorCode{-32804}, Message:\"Accumulate Error\", Data:\"invalid pending object entry error unmarshaling GenTransaction signature length out of range\"}"
},
"id": 4
}
```

Attached ~/.accumulate as zip archive
[Node0.zip](https://github.com/AccumulateNetwork/accumulated/files/7476399/Node0.zip)
e.

**Comment by firelizzard18** [comment]
This error has not recurred and running the commands above does not reproduce it on the current `develop` (bf14bc46506fc8ab576c5707c01ea41025eed896) so I'm closing it
