### ISSUE TITLE
Signer.PublicKey  is set twice

### ISSUE THREAD

**Issue by PaulBernier** [AccumulateNetwork/accumulate#378]
https://github.com/AccumulateNetwork/accumulate/blob/17ae42cf9edbb2dd4c638b18ccf5acd1324f1151/cmd/accumulate/cmd/util.go#L176
was already set earlier on line 166

**Comment by firelizzard18** [comment]
[!66](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/66) fixes this
