### ISSUE TITLE
Same key can be added multiple times to a Page

### ISSUE THREAD

**Issue by PaulBernier** [AccumulateNetwork/accumulate#379]
Tried to add the same key twice and it worked:
```
{
    "type": "keyPage",
    "merkleState": {
        "count": 4,
        "roots": [
            null,
            null,
            "f5dc2d85ca80ae45636e36259d3836044109436b587537a942de329ef195cd57"
        ]
    },
    "data": {
        "type": "keyPage",
        "url": "acc://luap/luap-page2",
        "keyBook": "acc://luap/my-book",
        "managerKeyBook": "",
        "creditBalance": 0,
        "keys": [
            {
                "publicKey": "8ebd6915084a24b41cc8a36b056a1439aee4da0fe8b6a4d884628f413b2dcfb0"
            },
            {
                "publicKey": "285b1528faf4a2da3fef25d17084212742374cfb273f81f2468e3f45780d135f"
            },
            {
                "publicKey": "285b1528faf4a2da3fef25d17084212742374cfb273f81f2468e3f45780d135f"
            }
        ]
    }
}
```
But documentation say that a Page is supposed to be a set. Not sure what are also the implication for "n of m" cases if the same key is present multiple times.

**Comment by PaulBernier** [comment]
Also if I later call to delete the key that appear twice, only one of them is deleted, so the key is still in the page, which could be  confusing for the user

**Comment by firelizzard18** [comment]
> Not sure what are also the implication for "n of m" cases if the same key is present multiple times.

That is a very good point and makes this more urgent than it would otherwise be. IIRC @PaulSnow you agree?

**Comment by firelizzard18** [comment]
Paul fixed this in [!45](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/45)
