### ISSUE TITLE
KeyBookUrl of CreateTokenAccount should be optional

### ISSUE THREAD

**Issue by PaulBernier** [AccumulateNetwork/accumulate#380]
https://github.com/AccumulateNetwork/accumulate/blob/develop/protocol/types_gen.go#L74
As per @firelizzard18 in Discord:

>  It should be optional for CreateTokenAccount. If you don't specify a key book, the new record will 'inherit' the key book of the ADI used to create it.

**Comment by firelizzard18** [comment]
Fixed by [!67](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/67)
