### ISSUE TITLE
Pagination parameter definition for QueryTxHistory is inconsistent with other query types

### ISSUE THREAD

**Issue by PaulBernier** [AccumulateNetwork/accumulate#381]
https://github.com/AccumulateNetwork/accumulate/blob/develop/internal/api/v2/methods.yml#L49
For `QueryTxHistory` it is defined as
```
call-params: [Url, Start, Count]
```
while `QueryDirectory` and `QueryDataSet` use `QueryPagination`.
While it seems that concretely they are equivalent it's unnecessarily confusing to have 2 styles of definition of pagination.

**Comment by firelizzard18** [comment]
This is a purely internal change, since none of that is exposed. But I went ahead and made [!68](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/68) to resolve it.
