### ISSUE TITLE
Duration JSON serialization (for Metrics API) is not language agnostic

### ISSUE THREAD

**Issue by PaulBernier** [AccumulateNetwork/accumulate#383]
The (de)serialization of the duration parameter for the metric API is bound to the Golang implementation: https://github.com/AccumulateNetwork/accumulate/blob/468cb4b16d7f18bb003aa2db17aacff2e17963e5/internal/encoding/utils.go#L266
which is hard/annoying to replicate for other languages. The API should be more universally friendly and accept something more universal, such as a number of seconds for instance instead.

**Comment by firelizzard18** [comment]
[!69](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/69) fixes this - Duration is now JSON serialized (and can be deserialized) as `{"seconds": 123, "nanoseconds": 456}`.

For reference (and for anyone coming across this in the future), the API can understand a duration passed as an integer or floating point number of seconds, as well as Go's string format for durations, in addition to the new form.

**Comment by PaulBernier** [comment]
> the API can understand a duration passed as an integer or floating point number of seconds
great, I didn't realize that
